name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.3.0

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run linters
        run: |
          yarn prettier --check .
          yarn eslint .

      - name: Run tests
        run: yarn run test

      - name: Run builds
        run: |
          yarn run build:api
          yarn run build:web
